aliases:
  - &root ~/instantsearchjs

  - &restore_node_modules
    name: Restore Yarn cache
    keys:
      - node_modules-{{ checksum "yarn.lock" }}

  - &save_node_modules
    name: Save Yarn cache
    key: node_modules-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

  - &attach_workspace
    at: *root

  - &persist_to_workspace
    root: *root

defaults: &defaults
  working_directory: *root
  docker:
    - image: circleci/node:12.14.1@sha256:84b5e98d5ad8dcce1ec7a024ffa06d087b9293b5872333650b3f1029b2038de7

version: 2
jobs:
  'install':
    <<: *defaults
    steps:
      - checkout
      - restore_cache: &restore_node_modules
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache: &save_node_modules
      - persist_to_workspace:
          <<: *persist_to_workspace
          paths:
            - ./*
  'build':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Build packages
          command: yarn run build
      - persist_to_workspace:
          <<: *persist_to_workspace
          paths:
            - cjs
            - dist
            - es
  'size check':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Test packages size
          command: yarn run test:size
  'unit tests':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Run unit tests
          command: yarn run test --maxWorkers=4
  'lint':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Lint & Code styles
          command: yarn run lint
  'type check':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Type Checking
          command: yarn run type-check
  'type check js (optional)':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Type Checking
          command: yarn run type-check:js
  'build storybook':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Build Storybook
          command: yarn run storybook:build
      - persist_to_workspace:
          <<: *persist_to_workspace
          paths:
            - website/stories
  'build examples':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Build Examples
          command: yarn run website:build
      - persist_to_workspace:
          <<: *persist_to_workspace
          paths:
            - website/examples
  'e2e tests':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: End-2-End tests
          command: yarn run test:e2e:saucelabs
  'release':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Trigger a release if the latest commit is a release commit
          command: yarn release:trigger
  'deploy':
    <<: *defaults
    steps:
      - attach_workspace: &attach_workspace
      - run:
          name: Deploy artifacts to netlify
          command: ls -la website

workflows:
  version: 2
  ci:
    jobs:
      - install
      - build:
          requires:
            - install
      - size check:
          requires:
            - build
      - unit tests:
          requires:
            - install
      - lint:
          requires:
            - install
      - type check:
          requires:
            - install
      - type check js (optional):
          requires:
            - install
      - build storybook:
          requires:
            - install
      - build examples:
          requires:
            - build
      - e2e tests:
          requires:
            - build examples
      - release:
          requires:
            - lint
            - type check
            - size check
            - unit tests
            - e2e tests
      - deploy:
          requires:
            - build examples
            - build storybook
